---
- hosts: all
  user: '{{ admin_user }}'

  roles:
    - role: elliotweiser.osx-command-line-tools
    - role: geerlingguy.mac.homebrew
      vars:
        homebrew_installed_packages:
          - chezmoi

  tasks:
    - import_tasks: tasks/ohmyzsh.yaml
    - import_tasks: tasks/ngram.yaml
    - import_tasks: tasks/chezmoi.yaml
      vars:
        chezmoi_user: '{{ admin_user }}'

    - name: Install brew apps
      include_role: 
        name: geerlingguy.mac.homebrew
      vars:
        homebrew_brewfile_dir: "~{{ admin_user }}/.config"
        homebrew_use_brewfile: true

    
    - import_tasks: tasks/nvim.yaml

    - name: 'Click login screen clock to show IP address, hostname, OS version, etc.' # TODO: Move to osx script
      shell: defaults write /Library/Preferences/com.apple.loginwindow AdminHostInfo HostName
      become: yes


  #   - role: geerlingguy.dotfiles
  #     when: configure_dotfiles
  #     tags: ['dotfiles']
  #   - role: geerlingguy.mac.mas
  #     when: mas_installed_apps or mas_installed_app_ids
  #     tags: ['mas']
  #   - role: geerlingguy.mac.dock
  #     when: configure_dock
  #     tags: ['dock']
  #
  # tasks:
  #   - import_tasks: tasks/sudoers.yml
  #     when: configure_sudoers
  #     tags: ['sudoers']
  #
  #   - import_tasks: tasks/terminal.yml
  #     when: configure_terminal
  #     tags: ['terminal']
  #
  #   - import_tasks: tasks/osx.yml
  #     when: configure_osx
  #     tags: ['osx']
  #
  #   - import_tasks: tasks/extra-packages.yml
  #     tags: ['extra-packages']
  #
  #   - block:
  #       - name: Run configured post-provision ansible task files.
  #         include_tasks: "{{ outer_item }}"
  #         loop_control:
  #           loop_var: outer_item
  #         with_fileglob: "{{ post_provision_tasks|default(omit) }}"
  #     tags: ['post']
