- name: Check NGrams
  stat: 
    path: '~{{ admin_user }}/ngrams'
  register: ngram_dir


- name: Make Ngram dir
  command: 'mkdir ~{{ admin_user }}/ngrams'
  when: not ngram_dir.stat.exists

- name: Download Ngrams DE
  command: curl https://languagetool.org/download/ngram-data/ngrams-de-20150819.zip --output ngrams-de.zip
  when: not ngram_dir.stat.exists

- name: Download Ngrams EN
  command: curl https://languagetool.org/download/ngram-data/ngrams-en-20150817.zip --output ngrams-en.zip
  when: not ngram_dir.stat.exists

- name: Unzip Ngrams DE
  command: unzip ngrams-de.zip -d ngrams   
  when: not ngram_dir.stat.exists

- name: Unzip Ngrams EN
  command: unzip ngrams-en.zip -d ngrams
  when: not ngram_dir.stat.exists

- name: Remove Zipfiles
  command: rm ngrams-de.zip ngrams-en.zip
  when: not ngram_dir.stat.exists
