---

- name: restart dock
  file:
    name: '{{ item }}'
    owner: '{{ username }}'
    group: staff
  with_items:
    - '{{ user_lib_prefs }}/com.apple.dock.plist'
    - '{{ user_lib_prefs }}/com.apple.screensaver.plist'
    - '{{ user_lib }}/Application Support/Dock'

notify:
    - kill dock

- name: kill dock
  shell: killall Dock
  ignore_errors: yes

